### ISSUE TITLE
cascading.json.JSONWritable cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by raphaelcm** [gmarabout-zz/cascading.json#2]
Data about events are reported in our logs as json strings, so I'm using cascading.json to parse them.

``` java
JSONParser parser = new JSONParser(new Fields("details"));
assembly = new Each(assembly, new Fields("details"), parser);
JSONSplitter splitter = new JSONSplitter(new Fields("user_id", "item_id"), "user_id", "item_id");
assembly = new Each(assembly, new Fields("details"), splitter);
// Output: (user_id item_id)
```

This works just fine.  I can output to a sink and see the user_id and item_id have been successfully parsed from the JSON.

However, if I add another step after this, like:

``` java
assembly = new GroupBy(assembly, new Fields("user_id"));
```

I get the following errors when I run the flow:

```
2013-02-13 22:33:00,928 INFO org.apache.hadoop.mapred.TaskInProgress: Error from attempt_201302111641_0048_m_000004_0: cascading.CascadingException: unable to compare Tuples, likely a CoGroup is being attempted on fields of different types or custom comparators are incorrectly set on Fields
    at cascading.tuple.hadoop.util.TupleElementComparator.compare(TupleElementComparator.java:80)
    at cascading.tuple.hadoop.util.TupleElementComparator.compare(TupleElementComparator.java:32)
    at cascading.tuple.hadoop.util.DelegatingTupleElementComparator.compare(DelegatingTupleElementComparator.java:74)
    at cascading.tuple.hadoop.util.DelegatingTupleElementComparator.compare(DelegatingTupleElementComparator.java:34)
    at cascading.tuple.hadoop.util.DeserializerComparator.compareTuples(DeserializerComparator.java:148)
    at cascading.tuple.hadoop.util.TupleComparator.compare(TupleComparator.java:38)
    at org.apache.hadoop.mapred.MapTask$MapOutputBuffer.compare(MapTask.java:1111)
    at org.apache.hadoop.util.QuickSort.sortInternal(QuickSort.java:70)
    at org.apache.hadoop.util.QuickSort.sort(QuickSort.java:59)
    at org.apache.hadoop.mapred.MapTask$MapOutputBuffer.sortAndSpill(MapTask.java:1399)
    at org.apache.hadoop.mapred.MapTask$MapOutputBuffer.flush(MapTask.java:1298)
    at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:437)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:372)
    at org.apache.hadoop.mapred.Child$4.run(Child.java:255)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:396)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1093)
    at org.apache.hadoop.mapred.Child.main(Child.java:249)
Caused by: java.lang.ClassCastException: cascading.json.JSONWritable cannot be cast to java.lang.String
    at java.lang.String.compareTo(String.java:92)
    at cascading.tuple.hadoop.util.TupleElementComparator$1.compare(TupleElementComparator.java:48)
    at cascading.tuple.hadoop.util.TupleElementComparator$1.compare(TupleElementComparator.java:35)
    at cascading.tuple.hadoop.util.TupleElementComparator.compare(TupleElementComparator.java:76)
    ... 17 more
```

Any idea how to resolve this?

Thank you for creating this library - it's very useful.

**Comment by raphaelcm** [comment]
I solved this by adding an identity function to coerce the values:

``` java
identity = new Identity(String.class, String.class);
assembly = new Each(assembly, new Fields("user_id", "item_id"), identity);
```

Closing.

**Comment by gmarabout-zz** [comment]
Thanks!
